/********************************************************************
* EventDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error EventDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEventDict();
extern void G__cpp_setup_inheritanceEventDict();
extern void G__cpp_setup_typetableEventDict();
extern void G__cpp_setup_memvarEventDict();
extern void G__cpp_setup_globalEventDict();
extern void G__cpp_setup_memfuncEventDict();
extern void G__cpp_setup_funcEventDict();
extern void G__set_cpp_environmentEventDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EventType.h"
#include "MonitorGUI.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EventDictLN_TClass;
extern G__linked_taginfo G__EventDictLN_TBuffer;
extern G__linked_taginfo G__EventDictLN_TMemberInspector;
extern G__linked_taginfo G__EventDictLN_TObject;
extern G__linked_taginfo G__EventDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__EventDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_TList;
extern G__linked_taginfo G__EventDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_stic_data_t;
extern G__linked_taginfo G__EventDictLN_TQObjSender;
extern G__linked_taginfo G__EventDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__EventDictLN_TGComboBox;
extern G__linked_taginfo G__EventDictLN_TGNumberEntry;
extern G__linked_taginfo G__EventDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__EventDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__EventDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_TSTiC2DAQ;
extern G__linked_taginfo G__EventDictLN_vectorlETSTiC2DAQcLcLmonitor_histcOallocatorlETSTiC2DAQcLcLmonitor_histgRsPgR;
extern G__linked_taginfo G__EventDictLN_reverse_iteratorlEvectorlETSTiC2DAQcLcLmonitor_histcOallocatorlETSTiC2DAQcLcLmonitor_histgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EventDictLN_maplEintcOstic_data_tcOlesslEintgRcOallocatorlEpairlEconstsPintcOstic_data_tgRsPgRsPgR;
extern G__linked_taginfo G__EventDictLN_MonitorGUI;

/* STUB derived class for protected member access */
